<?php
// @codingStandardsIgnoreFile
/**
 * @var $block \Smart2Pay\GlobalPay\Block\Info\Smart2Pay
 */
?>
<dl class="payment-method smart2pay">
    <dt class="title"><?php echo $block->escapeHtml($block->getMethod()->getTitle()) ?></dt>
    <?php if ($block->getInfo()->getAdditionalData()): ?>
        <?php if ($block->getInstructions()): ?>
            <dd class="content">
                <strong><?php echo $block->escapeHtml(__('Instructions')) ?></strong>
                <?php echo $block->escapeHtml($block->getInstructions()) ?>
            </dd>
        <?php endif; ?>
    <?php endif; ?>
</dl>
