<?php
// @codingStandardsIgnoreFile
/**
 * @var $block \Smart2Pay\GlobalPay\Block\Info\Smart2Pay
 */
?>
<?php echo $block->escapeHtml($block->getMethod()->getTitle()) ?>
    {{pdf_row_separator}}
<?php if ($block->getInfo()->getAdditionalData()): ?>
    {{pdf_row_separator}}
    <?php if ($block->getInstructions()): ?>
        <?php echo $block->escapeHtml(__('Instructions: %1', $block->getInstructions())) ?>
        {{pdf_row_separator}}
    <?php endif; ?>
<?php endif; ?>
