<?php
    // @codingStandardsIgnoreFile

    /** @var \Smart2Pay\GlobalPay\Block\Payment\Finish $block */

    $transaction_data = $block->getTransactionData();
?>
<div class="smart2pay-finish">
    <?php
    $error_message = $block->getErrorMessage();

    if( !empty( $error_message ) )
    {
        ?>
        <p><?php echo $error_message?></p>
        <div class="actions-toolbar">
            <div class="primary">
                <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
            </div>
        </div>
        <?php
    } else
    {
        ?>
        <h1><?php echo __( 'Thank you for shopping with us!' ) ?></h1>

        <h3><?php echo $block->getResultMessage()?></h3>

        <?php
        if( $block->getOrderId() )
        {
            if( $block->getCanViewOrder() )
            {
                ?><p><?php echo __( 'Your order number is: %1.', sprintf( '<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml( $block->getViewOrderUrl() ), $block->escapeHtml( $block->getOrderId() ) ) ) ?></p><?php
            }
            else
            {
                ?><p><?php echo __( 'Your order # is: <span>%1</span>.', $block->escapeHtml( $block->getOrderId() ) ) ?></p><?php
            }
        }
        ?>

        <div class="actions-toolbar">
            <div class="primary">
                <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
            </div>
        </div>
        <?php
    }
    ?>
</div>
