<?php
    // @codingStandardsIgnoreFile

    /** @var \Smart2Pay\GlobalPay\Block\Payment\Send $block */

    $smart2pay_details = $block->getSpDetails();
?>
<div class="checkout-success">
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()) :?>
            <p><?php echo __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php  else :?>
            <p><?php echo __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
        <?php endif;?>
        <p><?php /* @escapeNotVerified */ echo __('We\'ll email you an order confirmation with details and tracking info.') ?></p>
    <?php endif;?>

    <p><?php
        var_dump( $block->getData() );
    ?></p>
    <form name="smart2pay_payment_form" id="smart2pay_payment_form" method="post">
    <?php
        echo 'iiin form';
        var_dump( $smart2pay_details );
    ?>
    </form>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>
