<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @var $block \Smart2Pay\GlobalPay\Block\Info\Smart2Pay
 */
?>
<?php echo $block->escapeHtml($block->getMethod()->getTitle()) ?>
<?php if ($block->getInfo()->getAdditionalData()): ?>
    <?php if ($block->getInstructions()): ?>
        <br /><?php echo $block->escapeHtml(__('Instructions: %1', $block->getInstructions())) ?>
    <?php endif; ?>
<?php endif; ?>
