<?php
// @codingStandardsIgnoreFile
/**
 * @var $block \Smart2Pay\GlobalPay\Block\Form\Smart2Pay
 */
?>
bubukl
<?php if ($block->getMethod()->getMailingAddress() || $block->getMethod()->getPayableTo()): ?>
    <dl class="items check payable" id="payment_form_<?php echo $block->escapeHtml($block->getMethodCode()) ?>" style="display:none;">
        <?php if ($block->getMethod()->getPayableTo()): ?>
            <dt class="title"><?php echo $block->escapeHtml(__('Make Check payable to:')) ?></dt>
            <dd class="content"><?php echo $block->escapeHtml($block->getMethod()->getPayableTo()) ?></dd>
        <?php endif; ?>
        <?php if ($block->getMethod()->getMailingAddress()): ?>
            <dt class="title"><?php echo $block->escapeHtml(__('Send Check to:')) ?></dt>
            <dd class="content">
                <address class="checkmo mailing address">
                    <?php /* @noEscape */ echo nl2br($block->escapeHtml($block->getMethod()->getMailingAddress())) ?>
                </address>
            </dd>
        <?php endif; ?>
    </dl>
<?php endif; ?>
