<?php
/** @var \Smart2Pay\GlobalPay\Block\Adminhtml\System\Config\Field\Configuredmethods $block */
/** @var Magento\Framework\View\TemplateEngine\Php $this */
?>
</tbody></table>
<div style="clear:both;"></div>

<input type="hidden" value="1" name="groups[smart2pay][groups][smart2pay_methods][fields][configured_methods][value]" id="payment_smart2pay_smart2pay_methods_configured_methods" />
<input type="hidden" value="" name="groups[smart2pay][groups][smart2pay_methods][fields][configured_methods][action]" id="payment_smart2pay_smart2pay_methods_configured_methods_action" />

<style type="text/css">
.s2p-method-img-td { height:50px; width: 134px; text-align: center !important; }
.s2p-method-img { vertical-align: middle; max-height:40px; max-width:130px; }
.sp2-middle-all { text-align: center !important; vertical-align: middle !important; }
.sp2-middle-vertical { vertical-align: middle !important; }
#s2p_methods_table  { min-width: 450px; width: 100%; margin: 0; padding: 0; }
#s2p_methods_table th { padding: 2px; text-align: center; font-weight: bold; background-color: #b6b6b6; color: black; }
#s2p_methods_table td { padding: 2px; border-bottom: 1px solid black !important; }
</style>
<script type="text/javascript">
function s2p_config_js_select_all()
{
    form_obj = document.getElementById( 'config-edit-form' );
    if( form_obj && form_obj.elements && form_obj.elements.length )
    {
        for( i = 0; i < form_obj.elements.length; i++ )
        {
            if( form_obj.elements[i].type == 'checkbox' && form_obj.elements[i].name == 's2p_enabled_methods[]' )
            {
                if( !form_obj.elements[i].checked )
                    form_obj.elements[i].click();
            }
        }
    }
}
function s2p_config_js_deselect_all()
{
    form_obj = document.getElementById( 'config-edit-form' );
    if( form_obj && form_obj.elements && form_obj.elements.length )
    {
        for( i = 0; i < form_obj.elements.length; i++ )
        {
            if( form_obj.elements[i].type == 'checkbox' && form_obj.elements[i].name == 's2p_enabled_methods[]' )
            {
                if( form_obj.elements[i].checked )
                    form_obj.elements[i].click();
            }
        }
    }
}
function s2p_config_js_invert()
{
    form_obj = document.getElementById( 'config-edit-form' );
    if( form_obj && form_obj.elements && form_obj.elements.length )
    {
        for( i = 0; i < form_obj.elements.length; i++ )
        {
            if( form_obj.elements[i].type == 'checkbox' && form_obj.elements[i].name == 's2p_enabled_methods[]' )
            {
                form_obj.elements[i].click();
            }
        }
    }
}
function show_all_countries_for_method( method_id, action )
{
    if( typeof action == 'undefined' )
        action = 'noforce';

    var div_obj = jQuery('#s2p_meth_countries_'+method_id);

    if( (action == 'show' || div_obj.css('height') == '40px')
        && action != 'hide' )
    {
        div_obj.css('overflow', 'visible').css('height', 'auto');
    } else if( action == 'hide' || action == 'noforce' )
    {
        div_obj.css('overflow', 'hidden').css('height', '40px');
    }
}
function s2p_submit_sync_methods()
{
    jQuery( "#payment_smart2pay_smart2pay_methods_configured_methods_action" ).val( "do_sync" );
    //jQuery( "#payment_smart2pay_smart2pay_methods_configured_methods_action" ).closest("form").submit();
    jQuery( "#save" ).click();
}
</script>
<?php
    $environment = $block->get_environment();
    if( !($all_methods = $block->getAllActiveMethods( $environment, [ 'include_countries' => true ] )) )
        $all_methods = array();
    if( !($all_configured_methods = $block->getAllConfiguredMethods( $environment, [ 'only_active' => true ] )) )
        $all_configured_methods = array();

    if( !($last_sync_date = $block->get_last_sync_date()) )
        $last_sync_date = false;
    if( !($launch_sync_str = $block->seconds_to_launch_sync_str()) )
        $launch_sync_str = false;
    if( !($sdk_version = $block->get_sdk_version()) )
        $sdk_version = 'N/A';
?>
<div class="smart2pay_globalpay_configured_methods">
<div class="admin__control-table-wrapper">
<?php

    if( empty( $all_methods ) )
    {
        ?>
        <div style="text-align: center">
            SDK version: <?php echo $sdk_version?><br/>
            No payment methods defined in database for <strong><?php echo $environment?></strong> environment.
            In order to update payment methods, please select desired environment from Environment drop-down option and then save settings.<br/>
            <br/>
            Last syncronization: <?php echo (empty( $last_sync_date )?'Never':$last_sync_date)?><br/>
            <button type="button" value="Syncronize Now" title="Syncronize Now"
                    name="s2p_submit_syncronize_methods" id="s2p_submit_syncronize_methods"
                    onclick="s2p_submit_sync_methods()"
                    class="scalable save"><span><span>Syncronize Now</span></span></button>
        </div>
        <?php
    } else
    {
        ?>
        <div style="text-align: center">
            SDK version: <?php echo $sdk_version?><br/>
            Displaying payment methods for <strong><?php echo $environment?></strong> environment.
            In order to update payment methods for other environments please select desired environment from Environment drop-down option and then save settings.<br/>
            <br/>
            Last syncronization: <?php echo (empty( $last_sync_date )?'Never':$last_sync_date)?><br/>
            <?php
            if( empty( $launch_sync_str ) )
            {
                ?>
                <button type="submit" value="Syncronize Now" title="Syncronize Now"
                        name="s2p_submit_syncronize_methods" id="s2p_submit_syncronize_methods"
                        onclick="s2p_submit_sync_methods()"
                        class="scalable save"><span><span>Syncronize Now</span></span></button>
                <?php
            } else
            {
                ?>Time untill syncronization is available: <?php echo $launch_sync_str;?>.<?php
            }
            ?><br/><br/>
        </div>

        <table class="admin__control-table" id="s2p_methods_table">
        <thead>
        <tr>
            <th style="width: 30px;">#</th>
            <th style="width: 60px;"><?php echo __( 'Enabled?' )?></th>
            <th style="width: 90px;"><?php echo __( 'Surcharge' )?></th>
            <th colspan="2"><?php echo __( 'Method' )?></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td colspan="5">
                <p>
                    <a href="javascript:void(0);" onclick="s2p_config_js_select_all()">Select all</a>
                    |
                    <a href="javascript:void(0);" onclick="s2p_config_js_invert()">Invert</a>
                    |
                    <a href="javascript:void(0);" onclick="s2p_config_js_deselect_all()">Select none</a>
                </p>

            </td>
        </tr>
        <?php
        $knti = 1;
        foreach( $all_methods as $method_arr )
        {
            ?>
            <tr class="s2p-method-tr">
                <td class="sp2-middle-all"><?php echo $knti?></td>
                <td class="sp2-middle-all"><input type="checkbox" id="s2p_enabled_method_<?php echo $method_arr['method_id']?>" name="s2p_enabled_methods[]" value="<?php echo $method_arr['method_id']?>" <?php echo (!empty( $all_configured_methods[$method_arr['method_id']][0] )?'checked="checked"':'')?> /></td>
                <td class="sp2-middle-vertical" style="text-align: left;">
                    <div style="padding:2px; clear:both;"><input type="text" class="input-text" style="width: 50px !important; text-align: right;" name="s2p_surcharge[<?php echo $method_arr['method_id']?>]" id="s2p_surcharge_<?php echo $method_arr['method_id']?>" value="<?php echo ((!empty( $all_configured_methods[$method_arr['method_id']][0] ) and !empty( $all_configured_methods[$method_arr['method_id']][0]['surcharge'] ))?$all_configured_methods[$method_arr['method_id']][0]['surcharge']:0)?>"/>%</div>
                    <div style="padding:2px; clear:both;"><input type="text" class="input-text" style="width: 50px !important; text-align: right;" name="s2p_fixed_amount[<?php echo $method_arr['method_id']?>]" id="s2p_fixed_amount<?php echo $method_arr['method_id']?>" value="<?php echo ((!empty( $all_configured_methods[$method_arr['method_id']][0] ) and !empty( $all_configured_methods[$method_arr['method_id']][0]['fixed_amount'] ))?$all_configured_methods[$method_arr['method_id']][0]['fixed_amount']:0)?>"/> <?php echo $block->getBaseCurrency()?></div>
                </td>
                <td class="sp2-middle-all s2p-method-img-td"><img class="s2p-method-img" alt="<?php echo __( $method_arr['display_name'] ); ?>" src="<?php echo $method_arr['logo_url']?>" /></td>
                <td>
                    <label for="s2p_enabled_method<?php echo $method_arr['method_id']?>"><strong><?php echo __( $method_arr['display_name'] ); ?></strong></label>
                    <br/>
                    <?php echo __( $method_arr['description'] ); ?><br/>
                    <div id="s2p_meth_countries_<?php echo $method_arr['method_id']?>" style="height: 40px; overflow: hidden; text-overflow: ellipsis; display:block;">
                    <strong>Available in following countries</strong>:
                        (<a href="javascript:void(0);" style="text-decoration: underline;" onclick="show_all_countries_for_method( '<?php echo $method_arr['method_id']?>' )">toggle</a>)
                    <?php
                    if( empty( $method_arr['countries_list'] )
                     or !is_array( $method_arr['countries_list'] ) )
                        echo 'N/A';

                    else
                    {
                        $first = true;
                        foreach( $method_arr['countries_list'] as $country_id => $country_arr )
                        {
                            if( !$first )
                                echo ', ';

                            echo $country_arr['name'];
                            $first = false;

                        }
                        echo '.';
                    }
                    ?>
                    </div>
                </td>
            </tr>
            <?php
            $knti++;
        }
        ?>
        </tbody>
        </table>
    <?php
    }
    ?>
</div>
</div>

<table><tbody>
